spring:
  application:
    name: movie-catalog-service
resilience4j:
circuitbreaker:
  instances:
    movie-catalog-service:
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 10
      failureRateThreshold: 50
server:
  port: 8081